name: cats
description: What about cat's facts?

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-130.0.dev <3.2.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Date and number formatting and parsing
  intl: ^0.17.0

  # Bloc plugins
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # Hive plugins
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Http plugins
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.7.0

  # Work with images
  path_provider: ^2.0.11


  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  hive_generator: ^1.1.3
  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.4.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: ACDisplay
      fonts:
        - asset: fonts/ACDisplay-Bold.otf
          weight: 700
        - asset: fonts/ACDisplay-Bold.otf
          weight: 600
        - asset: fonts/ACDisplay-Regular.otf
          weight: 500
        - asset: fonts/ACDisplay-Regular.otf
        - asset: fonts/ACDisplay-Regular.otf
          weight: 300